### ISSUE TITLE
does it really use preact-router?

### ISSUE THREAD

**Issue by bboydflo** [developit/preact-todomvc#13]
Hi, I am trying to understand how to use preact-router, so I've checked this project source, but cannot find any mention of preact-router, other than in the dependencies...

**Comment by lukeed** [comment]
HI there! It does not. It used to, but was replaced with a `hashchange` listener instead.

This repo hasn't been updated in some time, FYI...

**Comment by developit** [comment]
@bboydflo I'd recommend creating a new [preact-cli](https://github.com/developit/preact-cli/) project and looking at how that works - it uses preact-router and is really quick & easy to get up and running.
