### ISSUE TITLE
Doesn't work in Firefox

### ISSUE THREAD

**Issue by ivanistheone** [developit/preact-todomvc#3]
To reproduce:

1. Visit https://preact-todomvc.surge.sh/ using Firefox
2. Start typing something

Expected: type a whole word

Actual: textbox loses focus after one keystroke

**Comment by addyosmani** [comment]
I similarly can't seem to get this working in Safari on iOS.

**Comment by developit** [comment]
Ah, likely just needs to be updated - this is running Preact 3 or 4, from ~march~ february.

**Comment by developit** [comment]
Updated it to preact 7 and rollup, and it now works in Firefox. It's also now 6kb :)
Cheers!
