### ISSUE TITLE
Dev server not serving static files

### ISSUE THREAD

**Issue by ivanistheone** [developit/preact-todomvc#4]
I was testing this app today, and wanted to see the hot module relooad in actoin. Running `npm run dev` however was not serving the static assets. Changing this line in `package.json`

      "dev": "webpack-dev-server",

to this

      "dev": "webpack-dev-server --content-base build",

fixes the problem.

It still 404s looking for some file called `learn.json`; not sure if that's important.

**Comment by developit** [comment]
Ahh very good catch! We can ignore the `learn.json` but the others you're absolutely right. I had changed this when switching to Rollup but didn't change `npm run dev`.

Are you able to PR your fix? Thanks!

**Comment by developit** [comment]
(Merged!)
